// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesOrderAPI.Infrastructure.Data;

#nullable disable

namespace SalesOrderAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260421203942_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address1 = "123 Business Street",
                            Address2 = "Suite 100",
                            Address3 = "",
                            Name = "Acme Corporation",
                            PostCode = "2000",
                            State = "NSW",
                            Suburb = "Sydney"
                        },
                        new
                        {
                            ClientId = 2,
                            Address1 = "456 Commerce Ave",
                            Address2 = "Level 5",
                            Address3 = "",
                            Name = "Global Industries",
                            PostCode = "3000",
                            State = "VIC",
                            Suburb = "Melbourne"
                        },
                        new
                        {
                            ClientId = 3,
                            Address1 = "789 Innovation Drive",
                            Address2 = "",
                            Address3 = "",
                            Name = "Tech Solutions Pty Ltd",
                            PostCode = "4000",
                            State = "QLD",
                            Suburb = "Brisbane"
                        });
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.ToTable("Item", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "Professional Consulting Services",
                            ItemCode = "ITEM001",
                            Price = 150.00m,
                            TaxRate = 0.10m
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Software License (Annual)",
                            ItemCode = "ITEM002",
                            Price = 1200.00m,
                            TaxRate = 0.10m
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "Technical Support Package",
                            ItemCode = "ITEM003",
                            Price = 500.00m,
                            TaxRate = 0.10m
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "Hardware Installation",
                            ItemCode = "ITEM004",
                            Price = 350.00m,
                            TaxRate = 0.10m
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "Training and Documentation",
                            ItemCode = "ITEM005",
                            Price = 250.00m,
                            TaxRate = 0.10m
                        });
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExcl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("SalesOrder", (string)null);
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.SalesOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal>("ExclAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InclAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("SalesOrderDetail", (string)null);
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("SalesOrderAPI.Domain.Entities.Client", "Client")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.SalesOrderDetail", b =>
                {
                    b.HasOne("SalesOrderAPI.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesOrderAPI.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.Client", b =>
                {
                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("SalesOrderAPI.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("SalesOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
